platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def asset_management
    pod 'Alamofire', '~> 4.7'
    pod 'Toast-Swift', '~> 4.0.0'
end

target 'AssetManagement' do
    asset_management
end
